### PR TITLE
Fix 64 bit integers on 32 bit platforms.

### PR DESCRIPTION
**Pull request by MerlijnWajer**
This commit fixes issue #2. I also took the liberty to clean up the usage of 32 bit integers.

### CODE REVIEW

**Comment by leo-bogert** [comment]
Hey!
Sorry for not having noticed this for a long time, somehow Github did not send me an Email.
I've added an entry to my personal TODO list to review this.

It may take some more weeks, but I shall definitely deal with it :)

Thanks for your work!

**Comment by MerlijnWajer** [comment]
Welcome. No rush - I have merged these changes in my own version (which is really just your program + these changes). So I'm not in a rush, just wanted to contribute these changes back. Thanks.

**Comment by MerlijnWajer** [comment]
*poke* ;-) 

I've submitted your code for inclusion in whipper/morituri - https://github.com/JoeLametta/whipper/pull/37 with my fixes. Hope that's OK (I think the license matches)

**Comment by ArchangeGabriel** [comment]
@leo-bogert Any news here? :)

**Comment by Phaaxood** [comment]
Any progress here =)?

**Comment by MerlijnWajer** [comment]
You might want to check out whipper, it contains a fixed version iirc: https://github.com/JoeLametta/whipper/

**Comment by Phaaxood** [comment]
@MerlijnWajer thanks, it does and I know that =). I'm just trying to get the packages included in Archlinux32 to work and they still use this repo as the source. So I thought asking here will not hurt. I'm using whipper with it's version on my laptop.

**Comment by leo-bogert** [comment]
Oh I wasn't aware that my stuff was included in Arch, that's nice.

I'll prioritize merging this soon then, sorry for the long wait. I've been developing other stuff meanwhile.
But being included in a distribution motivates me to dedicate some time to this :)

**Review by leo-bogert — COMMENTED** [review]
Can you please clarify *what* this fixes?
E.g. the compiler error message?

I don't write C very often so I'd also appreciate a hint to the documentation which justifies using these types intstead. Not a blocker though :)

Thanks!

**Comment by leo-bogert** [comment]
Oh damn I missed the bugtracker entry which provides the error message, sorry.
Nevermind then, I'll merge it the following days once I am at my workstation! :)

**Comment by leo-bogert** [comment]
Merged :) I've also improved the README and added a makefile.

If you have further improvements in your forks of this please send pull requests for them now - given that I've just refreshed my knowledge of how this works it'd be good if I deal with merging everything else soon :)

Further I'd be interested in knowing the places where to ask maintainers of e.g. distribution packages or other stuff which uses this to pull the updated code.

And finally if someone can confirm this still works as desired I'd appreciate that, I currently have no music at hand to test it with.

Thanks again & sorry for the huge delay!

**Comment by Phaaxood** [comment]
Works like the local version I patched for my use on at least one file =). The old version crashed on that one, so it looks good to me.

I just flagged the package in Arch to be out of date: https://www.archlinux.org/packages/community/x86_64/accuraterip-checksum/

**Pull request merged**
